'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Presentacion.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boton_eliminar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_eliminar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Listado de clientes&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''        }
        '''
        '''        h1 {
        '''            text-align: center;
        '''        }
        '''
        '''        table {
        '''            width: 100%;
        '''            border-collapse: collapse;
        '''        }
        '''
        '''        th, td {
        '''            padding: 10px;
        '''            text-align: left;
        '''            border-bottom: 1px solid #ddd;
        '''        }
        '''
        '''        th {
        '''            background-color: #f2f2f2;
        '''         [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Categorias() As String
            Get
                Return ResourceManager.GetString("Categorias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Listado de clientes&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''        }
        '''
        '''        h1 {
        '''            text-align: center;
        '''        }
        '''
        '''        table {
        '''            width: 100%;
        '''            border-collapse: collapse;
        '''        }
        '''
        '''        th, td {
        '''            padding: 10px;
        '''            text-align: left;
        '''            border-bottom: 1px solid #ddd;
        '''        }
        '''
        '''        th {
        '''            background-color: #f2f2f2;
        '''         [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Clientes() As String
            Get
                Return ResourceManager.GetString("Clientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Listado de clientes&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''        }
        '''
        '''        h1 {
        '''            text-align: center;
        '''        }
        '''
        '''        table {
        '''            width: 100%;
        '''            border-collapse: collapse;
        '''        }
        '''
        '''        th, td {
        '''            padding: 10px;
        '''            text-align: left;
        '''            border-bottom: 1px solid #ddd;
        '''        }
        '''
        '''        th {
        '''            background-color: #f2f2f2;
        '''        }
        '''
        '''        footer {
        '''       [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExportarpdfListadoCompras() As String
            Get
                Return ResourceManager.GetString("ExportarpdfListadoCompras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;/head&gt;
        '''&lt;body&gt;
        '''    &lt;h1&gt;Reporte PDF&lt;/h1&gt;
        '''
        '''    &lt;table&gt;
        '''        &lt;thead&gt;
        '''            &lt;tr&gt;
        '''                &lt;!--&lt;th&gt;No Factura&lt;/th&gt;
        '''                &lt;th&gt;Fecha&lt;/th&gt;
        '''                &lt;th&gt;Codigo Cliente&lt;/th&gt;
        '''                &lt;th&gt;Descuento&lt;/th&gt;
        '''                &lt;th&gt;Monto Total&lt;/th&gt;
        '''                &lt;th&gt;Estado&lt;/th&gt;--&gt;
        '''                &lt;th&gt;&lt;/th&gt;
        '''                &lt;th&gt;&lt;/th&gt;
        '''                &lt;th&gt;&lt;/th&gt;
        '''                &lt;th&gt;&lt;/th&gt;
        '''                &lt;th&gt;&lt;/th&gt;
        '''                &lt;th&gt;&lt;/th&gt;
        '''            &lt;/tr&gt;
        '''        &lt;/thead&gt;
        '''        &lt;tbody&gt;
        '''  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExportarpdfListaVenta() As String
            Get
                Return ResourceManager.GetString("ExportarpdfListaVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;title&gt;Factura de Compra&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''            background-color: #f2f2f2;
        '''            margin: 20px;
        '''        }
        '''
        '''        .container {
        '''            background-color: #fff;
        '''            padding: 20px;
        '''            border-radius: 10px;
        '''            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        '''        }
        '''
        '''        table {
        '''            width: 100%;
        '''            border-collapse: collapse;
        '''           [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Factura() As String
            Get
                Return ResourceManager.GetString("Factura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;title&gt;Factura de Venta&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''            background-color: #f8f8f8;
        '''            margin: 0;
        '''            padding: 20px;
        '''        }
        '''
        '''        .container {
        '''            max-width: 800px;
        '''            margin: 0 auto;
        '''            background-color: #fff;
        '''            padding: 20px;
        '''            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        '''        }
        '''
        '''        .header {
        '''            display: fle [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property FacturaV() As String
            Get
                Return ResourceManager.GetString("FacturaV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ojo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ojo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ojo_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ojo_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Listado productos&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''        }
        '''
        '''        h1 {
        '''            text-align: center;
        '''        }
        '''
        '''        table {
        '''            width: 100%;
        '''            border-collapse: collapse;
        '''        }
        '''
        '''        th, td {
        '''            padding: 10px;
        '''            text-align: left;
        '''            border-bottom: 1px solid #ddd;
        '''        }
        '''
        '''        th {
        '''            background-color: #f2f2f2;
        '''        }        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Productos() As String
            Get
                Return ResourceManager.GetString("Productos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Listado proveedores&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''        }
        '''
        '''        h1 {
        '''            text-align: center;
        '''        }
        '''
        '''        table {
        '''            width: 100%;
        '''            border-collapse: collapse;
        '''        }
        '''
        '''        th, td {
        '''            padding: 10px;
        '''            text-align: left;
        '''            border-bottom: 1px solid #ddd;
        '''        }
        '''
        '''        th {
        '''            background-color: #f2f2f2;
        '''         [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Proveedor() As String
            Get
                Return ResourceManager.GetString("Proveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Reporte PDF&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body {
        '''            font-family: Arial, sans-serif;
        '''        }
        '''
        '''        h1 {
        '''            text-align: center;
        '''        }
        '''
        '''        table {
        '''            width: 100%;
        '''            border-collapse: collapse;
        '''        }
        '''
        '''        th, td {
        '''            padding: 10px;
        '''            text-align: left;
        '''            border-bottom: 1px solid #ddd;
        '''        }
        '''
        '''        th {
        '''            background-color: #f2f2f2;
        '''        }
        '''
        '''        tbody tr:nth-child(odd) [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Usuario() As String
            Get
                Return ResourceManager.GetString("Usuario", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
